// AUTOMATICALLY GENERATED BY GRADLE
// Generated at: 1769007475186

#pragma once
#include <vector>
#include <cstdint>

static const int EXPECTED_DEX_COUNT = 3;
static const uint32_t EXPECTED_DEX_CRCS[] = { 0xC0FF7926, 0x6E361152, 0x2EBD34B0 };