// AUTOMATICALLY GENERATED BY GRADLE
// Generated at: 1769007860653

#pragma once
#include <vector>
#include <cstdint>

static const int EXPECTED_DEX_COUNT = 3;
static const uint32_t EXPECTED_DEX_CRCS[] = { 0x9B00C5C3, 0xFDE4387A, 0x360D14E9 };