// AUTOMATICALLY GENERATED BY GRADLE
// Generated at: 1769007215344

#pragma once
#include <vector>
#include <cstdint>

static const int EXPECTED_DEX_COUNT = 3;
static const uint32_t EXPECTED_DEX_CRCS[] = { 0x9B00C5C3, 0xE0FF5D15, 0x360D14E9 };